[package]
name = "exploit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rlibc = "1.0.0"

[profile.dev]
panic = "abort"

[inner_unikernel]
helpers = [
    "prepare_kernel_cred",
    "commit_creds"
]
